description: All about me
datelastupdated: July, 2026
fullnameofperson: Belinda Weaver
selfIdentification: Substack warrior
colour1: "#2F4F4F"  # sidebar background 
colour2: "#F8F8FF"  # colour of name and desc
colour3: "#F8F8FF"  # colour of Menu links
colour4: "#d4dfc7" # trying to be background colour - still experimenting 
colour5: "#e7ecef" # menu link colour when hover
