description: All about me
datelastupdated: February, 2022
fullnameofperson: Belinda Weaver
selfIdentification: Science student, The University of Queensland
colour1: "#2F4F4F"  # sidebar background 
colour2: "#F8F8FF"  # colour of name and desc
colour3: "#F8F8FF"  # colour of Menu links
colour4: "#d4dfc7" # trying to be background colour - still experimenting 
colour5: "#e7ecef" # menu link colour when hover
